export const MOCK_CONTAINERS = [
  {
    id: "CNT-001",
    containerNumber: "CNT-001",
    caseNumber: "CASE-2024-001",
    mblNumber: "MBL-001234567",
    size: "40ft",
    terminal: "Port of Los Angeles",
    deliveryAddressCompany: "ABC Logistics, Dallas, TX",
    appointmentTime: "2024-12-15T10:00:00",
    lfd: "2024-12-20",
    eta: "2024-12-18",
    billingParty: "ABC Logistics",
    demurrage: "$150/day",
    inputPerson: "John Dispatcher",
    notes: "Standard shipment",
    deliveryAppointment: "Dec 21, 2024 at 2:00 PM",
    emptyStatus: "Empty",
    rtLocEmptyApp: "Terminal A - Dec 22",
    yards: "Yard 3",
    puDriver: "John Smith", // Added PU DRIVER
  },
  {
    id: "CNT-002",
    containerNumber: "CNT-002",
    caseNumber: "CASE-2024-002",
    mblNumber: "MBL-002345678",
    size: "20ft",
    terminal: "Port of Long Beach",
    deliveryAddressCompany: "XYZ Supply Co, Chicago, IL",
    appointmentTime: "2024-12-16T14:00:00",
    lfd: "2024-12-22",
    eta: "2024-12-20",
    billingParty: "XYZ Supply Co",
    demurrage: "$100/day",
    inputPerson: "Sarah Manager",
    notes: "Fresh produce - maintain temp",
    deliveryAppointment: "Dec 23, 2024 at 9:00 AM",
    emptyStatus: "Full",
    rtLocEmptyApp: "Warehouse B - Dec 24",
    yards: "Yard 1",
    puDriver: "Maria Garcia", // Added PU DRIVER
  },
  {
    id: "CNT-003",
    containerNumber: "CNT-003",
    caseNumber: "CASE-2024-003",
    mblNumber: "MBL-003456789",
    size: "40ft",
    terminal: "Houston Port",
    deliveryAddressCompany: "Global Trade Inc, Miami, FL",
    appointmentTime: "2024-12-17T08:00:00",
    lfd: "2024-12-19",
    eta: "2024-12-17",
    billingParty: "Global Trade Inc",
    demurrage: "$175/day",
    inputPerson: "Mike Coordinator",
    notes: "Electronics shipment",
    deliveryAppointment: "Dec 18, 2024 at 11:00 AM",
    emptyStatus: "Full",
    rtLocEmptyApp: "Port Terminal - Dec 19",
    yards: "Yard 5",
    puDriver: "Robert Johnson", // Added PU DRIVER
    driverId: "DRV-001",
    chassisId: "CHS-001",
  },
  {
    id: "CNT-004",
    containerNumber: "CNT-004",
    caseNumber: "CASE-2024-004",
    mblNumber: "MBL-004567890",
    size: "20ft",
    terminal: "Port of Los Angeles",
    deliveryAddressCompany: "Desert Freight, Las Vegas, NV",
    appointmentTime: "2024-12-14T11:00:00",
    lfd: "2024-12-18",
    eta: "2024-12-14",
    billingParty: "Desert Freight",
    demurrage: "$125/day",
    inputPerson: "John Dispatcher",
    notes: "Delivered on time",
    deliveryAppointment: "Dec 15, 2024 at 1:00 PM",
    emptyStatus: "Empty",
    rtLocEmptyApp: "Yard 5 - Dec 16",
    yards: "Yard 2",
    puDriver: "Sarah Williams", // Added PU DRIVER
    driverId: "DRV-002",
    chassisId: "CHS-002",
  },
  {
    id: "CNT-005",
    containerNumber: "CNT-005",
    caseNumber: "CASE-2024-005",
    mblNumber: "MBL-005678901",
    size: "40ft",
    terminal: "Port of Houston",
    deliveryAddressCompany: "Northeast Distribution, Philadelphia, PA",
    appointmentTime: "2024-12-18T09:00:00",
    lfd: "2024-12-25",
    eta: "2024-12-23",
    billingParty: "Northeast Distribution",
    demurrage: "$200/day",
    inputPerson: "Sarah Manager",
    notes: "Hazardous materials - special handling required",
    deliveryAppointment: "Dec 26, 2024 at 10:00 AM",
    emptyStatus: "Full",
    rtLocEmptyApp: "Depot C - Dec 27",
    yards: "Yard 4",
    puDriver: "Michael Chen", // Added PU DRIVER
  },
]

export const MOCK_DRIVERS = [
  {
    id: "DRV-001",
    name: "John Smith",
    phone: "+1-555-0101",
    licenseNumber: "DL123456",
    status: "Assigned" as const,
  },
  {
    id: "DRV-002",
    name: "Maria Garcia",
    phone: "+1-555-0102",
    licenseNumber: "DL789012",
    status: "Available" as const,
  },
  {
    id: "DRV-003",
    name: "Robert Johnson",
    phone: "+1-555-0103",
    licenseNumber: "DL345678",
    status: "Off Duty" as const,
  },
  {
    id: "DRV-004",
    name: "Sarah Williams",
    phone: "+1-555-0104",
    licenseNumber: "DL901234",
    status: "Available" as const,
  },
  {
    id: "DRV-005",
    name: "Michael Chen",
    phone: "+1-555-0105",
    licenseNumber: "DL567890",
    status: "Assigned" as const,
  },
]

export const MOCK_CHASSIS = [
  {
    id: "CHS-001",
    licensePlate: "ABC-1234",
    type: "Standard Flatbed",
    status: "In Use" as const,
  },
  {
    id: "CHS-002",
    licensePlate: "XYZ-5678",
    type: "Refrigerated",
    status: "Available" as const,
  },
  {
    id: "CHS-003",
    licensePlate: "DEF-9012",
    type: "Low Boy",
    status: "Maintenance" as const,
  },
  {
    id: "CHS-004",
    licensePlate: "GHI-3456",
    type: "Standard Flatbed",
    status: "Available" as const,
  },
  {
    id: "CHS-005",
    licensePlate: "JKL-7890",
    type: "Tanker",
    status: "In Use" as const,
  },
]

export const mockContainers = MOCK_CONTAINERS
export const mockDrivers = MOCK_DRIVERS
export const mockChassis = MOCK_CHASSIS
